### ISSUE TITLE
Can the binaries be cached?

### ISSUE THREAD

**Issue by brian-kephart** [Verumex/heroku-buildpack-vips#1]
This buildpack seems like the easiest way to get vips into a Heroku app, so well done. Every other buildpack I found had additional dependencies.

I was wondering if it could be modified to cache the compiled binaries, though, so that they don't have to be re-compiled on every deploy unless the version changes. Heroku provides a cache directory, but I suck at Bash too much to (quickly) figure out how to get it done.

Thoughts?

**Comment by karunsiri** [comment]
Thank you for the suggestion @brian-kephart! It's a good idea to make use of the already provided cache directory to store build artifacts to speed up the builds.
At times of creating this buildpack we aimed to have libvips installed with no other dependencies. We haven't really thought of the wait time between builds.

Just to cover your question, yes, the build artifacts could be cached, by version. 

You are welcome to contribute to this buildpack 😉.
You may take a look at `/bin/compile` script. The script will source `/bin/buildscript.sh`, so all the build steps are actually there. 

We may implement the build in the future. 
Thank you again for the idea!

**Comment by karunsiri** [comment]
Closes via https://github.com/Verumex/heroku-buildpack-libvips/pull/2
